// const BASE_URL = "http://188.166.251.24:17076";
const BASE_URL = "http://188.166.251.24:37076";
const EA_MOBILES = "/ea/mobiles";
const SECRET_KEY = "a8eeea6c3c839d8b96a8a1a43a13e5c3";
const ANIPAY_LOGIN = "1000";
const ANIPAY_USER_REGISTRATION = "1111";

const EXAMPLE_HASHED_REGISTER_RESPONSE = """GEQiTUZIRBpKFUJkBl0JSgdfWjQjNBJCBxA0RkkJSQZNAl1_BQQ0ITY3aSwnL2g8NRYJdkoGQzQfPw0ERwtZCFN_Tgh1enNbdQZOCzZPfFIGXllzXHsCZ1hJBAI3C1EHSQVIdWQFMjl5S31cWFx2XHwkB0IZQxJCFRRCEhRGG0caSEhkBTZoKDQmYjIEPQ5KBVNIeiMyGkQcF0oaFE4WRRRDGUlGSXE1AwRqKgQsWCozRltuXUwCQxUcQhQUThZMFEMZR0ZJQhpzNHVcV2EEW3ckB2ZOBUFDFxdxMi1kIDQbSR9MdWlzU3hTTgkUSWpXB19SMjZ3TnNTTgdWT3dUNDgESgQJd31afUNnUlBLfVR0WAdmWAJXAgVPdwIyBQZqJTIqBHp3NGRxEDZcWEsHXTUkCTQVNFYBWUV""";
const EXAMPLE_REGISTER_RESPONSE_JSON = """{'status': '00', 'description': 'SUCCESS','data': 'GEQiTUZIRBpKFUJkBl0JSgdfWjQjNBJCBxA0RkkJSQZNAl1_BQQ0ITY3aSwnL2g8NRYJdkoGQzQfPw0ERwtZCFN_Tgh1enNbdQZOCzZPfFIGXllzXHsCZ1hJBAI3C1EHSQVIdWQFMjl5S31cWFx2XHwkB0IZQxJCFRRCEhRGG0caSEhkBTZoKDQmYjIEPQ5KBVNIeiMyGkQcF0oaFE4WRRRDGUlGSXE1AwRqKgQsWCozRltuXUwCQxUcQhQUThZMFEMZR0ZJQhpzNHVcV2EEW3ckB2ZOBUFDFxdxMi1kIDQbSR9MdWlzU3hTTgkUSWpXB19SMjZ3TnNTTgdWT3dUNDgESgQJd31afUNnUlBLfVR0WAdmWAJXAgVPdwIyBQZqJTIqBHp3NGRxEDZcWEsHXTUkCTQVNFYBWUV-BB44CEAGdkoKd0g0IQ9hQAtXTwhcfFlVNCM0BA8'}""";
const USER_PROFILE_NAMA_USER = "user_profile_nama_user";
const USER_PROFILE_NAMA_LOKET = "user_profile_nama_loket";
const USER_PROFILE_NOMOR_REGISTRASI = "user_profile_nomor_registrasi";
const USER_PROFILE_NO_VA_MYNT = "user_profile_no_va_mynt";
const USER_PROFILE_EMAIL = "user_profile_email";
const USER_PROFILE_NO_PONSEL = "user_profile_no_ponsel";
const USER_PROFILE_PEKERJAAN = "user_profile_pekerjaan";
const USER_PROFILE_ALAMAT = "user_profile_alamat";
